apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  

spec:
  replicas: 1
  selector:              # component it is going to manage
    matchLabels:
      component: web
  template:              # is how deployment gonna identify different pods it is going to manage
    metadata:
      labels:
        component: web
    spec:
      containers:
      - name: client
        image: sudeep254/python-redis-postgres:latest 
        ports:
          - containerPort: 8000
        env:
          - name: REDIS_HOST
            value: redis-cluster-ip-service
          - name: REDIS_PORT
            value: '6379'
          - name: POSTGRES_DB
            value: linode
          - name: POSTGRES_HOST
            value: postgres-cluster-ip-service
          - name: POSTGRES_PORT
            value: '5432'
          - name: DB_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pgpassword
                key: POSTGRES_PASSWORD
            

  

      