apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    name: database-persistent-volume-claim
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"