apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistant-volume-claim
  
  
spec:
  # The metadata.name field from the PersistentVolume to match
  volumeName: volumeName
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      # The amount of the volume's storage to request
      storage: 2Gi